name: GameNite CI
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  basic-checks:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: npm ci

      - name: Typescript
        run: npm run check

      - name: Formatting
        run: npm run prettier

      - name: Linting
        run: npm run lint

      - name: Build frontend
        run: npm run build -w=client

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: npm run test

      - name: Test that the backend server starts
        run: |
          npm start -w=server & sleep 5
          echo "Checking if home page is served"
          curl --fail 'http://localhost:8000/' > /dev/null 2>&1

          echo "Checking if login page is served"
          curl --fail 'http://localhost:8000/login' > /dev/null 2>&1

          echo "Checking if api endpoint returns several threads"
          curl --fail 'http://localhost:8000/api/thread/list' 2> /dev/null | jq 'if length < 4 then error("Too few posts returned from api") else . end'

      - name: Kill any node processes from previous step
        if: ${{ always() }}
        run: killall node || true
